<?php
require '/wordpress/wp-load.php';wp_set_current_user(1);
function code_test($condition,$message){if(!$condition)throw new Exception($message);}
$source=wp_insert_post(['post_type'=>'qrp_item','post_status'=>'publish','post_title'=>'Kod źródłowy']);$target=wp_insert_post(['post_type'=>'qrp_item','post_status'=>'publish','post_title'=>'Nowy cel QR']);$draft=wp_insert_post(['post_type'=>'qrp_item','post_status'=>'draft','post_title'=>'Niedostępny cel']);
$png=wp_insert_attachment(['post_mime_type'=>'image/png','post_title'=>'QR testowy','post_status'=>'inherit'],'',$source);$svg=wp_insert_attachment(['post_mime_type'=>'image/svg+xml','post_title'=>'QR testowy SVG','post_status'=>'inherit'],'',$source);update_post_meta($source,'qrp_qr_png',$png);update_post_meta($source,'qrp_qr_svg',$svg);$token=qrp_token($source);$url=qrp_scan_url($source);
$request=new WP_REST_Request('POST','/qr-pelplin/v1/codes/'.$source);$request->set_header('Content-Type','application/json');$request->set_body(wp_json_encode(['target_id'=>$target]));$response=rest_do_request($request);code_test($response->get_status()===200,'Admin may reassign code');code_test(qrp_qr_target(get_post($source))->ID===$target,'Resolver points directly to selected entry');code_test(qrp_token($source)===$token&&qrp_scan_url($source)===$url,'Printed QR address unchanged');code_test((int)get_post_meta($source,'qrp_qr_png',true)===$png&&(int)get_post_meta($source,'qrp_qr_svg',true)===$svg,'Original download attachments unchanged');
$request->set_body(wp_json_encode(['target_id'=>$draft]));code_test(rest_do_request($request)->get_status()===400,'Draft target rejected');code_test(qrp_qr_target(get_post($source))->ID===$target,'Rejected assignment leaves existing target intact');wp_update_post(['ID'=>$target,'post_password'=>'protected']);code_test(qrp_qr_target(get_post($source))===false,'Protected target becomes unavailable');wp_update_post(['ID'=>$target,'post_password'=>'']);
$list=rest_do_request(new WP_REST_Request('GET','/qr-pelplin/v1/codes'));$rows=$list->get_data()['items'];code_test(count(array_filter($rows,function($row)use($source){return $row['id']===$source&&$row['target_id']>0;}))===1,'Generated codes appear in registry');
$author=wp_insert_user(['user_login'=>'qrp_code_author','user_pass'=>'test-password','role'=>'author']);wp_set_current_user($author);$request->set_body(wp_json_encode(['target_id'=>$source]));code_test(rest_do_request($request)->get_status()===403,'Author cannot redirect printed codes');wp_set_current_user(0);code_test(rest_do_request(new WP_REST_Request('GET','/qr-pelplin/v1/codes'))->get_status()===401,'Anonymous cannot enumerate private code registry');wp_set_current_user(1);
wp_trash_post($source);code_test(qrp_qr_target(get_post($source))->ID===$target,'Reassigned code survives source entering trash');update_post_meta($source,'qrp_qr_target',$source);code_test(qrp_qr_target(get_post($source))===false,'Unassigned trashed source remains unavailable');
echo 'QR REGISTRY TESTS PASSED';
