<?php defined('ABSPATH') || exit; $term=get_queried_object(); $query=qrp_content_query(['category'=>$term->term_id,'page'=>max(1,(int)get_query_var('paged'))]); ?>
<section class="qrp-section qrp-archive" data-content data-count="<?php echo absint($s['content_count']); ?>" data-category="<?php echo absint($term->term_id); ?>" data-page="<?php echo max(1,absint(get_query_var('paged'))); ?>">
<a class="qrp-text-link" href="<?php echo esc_url(qrp_landing_url().'#kategorie'); ?>">← Wszystkie kategorie</a>
<header class="qrp-archive-heading"><p class="qrp-eyebrow">ODKRYWAJ PELPLIN · KATEGORIE</p><h1><?php echo esc_html($term->name); ?></h1><?php if($term->description): ?><p><?php echo esc_html(wp_strip_all_tags($term->description)); ?></p><?php endif; ?></header>
<nav class="qrp-category-tabs" aria-label="Kategorie treści"><?php $terms=get_terms(['taxonomy'=>'qrp_category','hide_empty'=>false]);if(!is_wp_error($terms))foreach($terms as $category): ?><a href="<?php echo esc_url(get_term_link($category)); ?>" <?php if($category->term_id===$term->term_id)echo 'aria-current="page"'; ?>><?php echo esc_html($category->name); ?></a><?php endforeach; ?></nav>
<div class="qrp-section-heading"><h2>Treści w kategorii</h2><span class="qrp-total"><?php echo absint($query->found_posts); ?> treści</span></div>
<?php if($s['show_search']): ?><form class="qrp-search" role="search"><label class="screen-reader-text" for="qrp-search">Szukaj w tej kategorii</label><input id="qrp-search" name="search" type="search" placeholder="Szukaj w tej kategorii…"><input type="hidden" name="category" value="<?php echo absint($term->term_id); ?>"><button class="qrp-button" type="submit">Szukaj →</button></form><?php endif; ?>
<div class="qrp-content-grid" data-grid><?php qrp_cards($query->posts); ?></div><p data-content-status role="status"><?php if(!$query->post_count)echo 'W tej kategorii nie ma jeszcze opublikowanych treści.'; ?></p><button class="qrp-outline" data-more <?php if($query->max_num_pages<=max(1,(int)get_query_var('paged')))echo 'hidden'; ?>>Pokaż kolejne treści ↓</button>
<noscript><?php echo paginate_links(['total'=>$query->max_num_pages,'current'=>max(1,(int)get_query_var('paged'))]); ?></noscript>
</section>
