<?php defined('ABSPATH') || exit; $hero=qrp_image($s['hero_image'])?:QRP_URL.'assets/hero.jpg'; ?>
<div class="qrp-landing qrp-font-<?php echo esc_attr($s['font']); ?>">
<?php echo qrp_template('hero',['s'=>$s]); ?>
<?php foreach($s['modules'] as $module): if(!$module['enabled']) continue; switch($module['type']): case 'features': ?>
<?php echo qrp_template('features',['s'=>$s]); ?>
<?php break; case 'categories': $categories=get_terms(['taxonomy'=>'qrp_category','hide_empty'=>false,'number'=>$s['category_count']]); ?>
<section id="kategorie" class="qrp-section"><div class="qrp-section-heading"><div><p class="qrp-eyebrow">OD HISTORII DO CODZIENNOŚCI</p><h2><?php echo esc_html($s['categories_title']); ?></h2></div><a href="#tresci" class="qrp-text-link">Zobacz treści <span>→</span></a></div><div class="qrp-category-grid">
<?php if(!is_wp_error($categories)) foreach($categories as $index=>$term): $img=qrp_image($s['category_images'][$term->term_id]??0)?:QRP_URL.'assets/hero.jpg'; ?><a class="qrp-category" href="<?php echo esc_url(get_term_link($term)); ?>"><img src="<?php echo esc_url($img); ?>" alt="" loading="lazy"><div><span class="qrp-category-number"><?php echo esc_html(sprintf('%02d',$index+1)); ?></span><h3><?php echo esc_html($term->name); ?></h3><span class="qrp-circle" aria-hidden="true">→</span></div></a><?php endforeach; ?>
</div></section>
<?php break; case 'content': $query=qrp_content_query(); ?>
<section id="tresci" class="qrp-section" data-content data-count="<?php echo absint($s['content_count']); ?>"><div class="qrp-section-heading"><div><p class="qrp-eyebrow">MIEJSCA, LUDZIE, OPOWIEŚCI</p><h2><?php echo esc_html($s['content_title']); ?></h2></div><span class="qrp-total"><?php echo absint($query->found_posts); ?> treści</span></div>
<?php if($s['show_search']): ?><form class="qrp-search" role="search"><label class="screen-reader-text" for="qrp-search">Szukaj treści</label><input id="qrp-search" name="search" placeholder="Szukaj historii, miejsc, ciekawostek…" type="search"><label class="screen-reader-text" for="qrp-category">Kategoria</label><select id="qrp-category" name="category"><option value="">Wszystkie kategorie</option><?php $terms=get_terms(['taxonomy'=>'qrp_category','hide_empty'=>false]);if(!is_wp_error($terms))foreach($terms as $t)echo '<option value="'.absint($t->term_id).'">'.esc_html($t->name).'</option>'; ?></select><button class="qrp-button" type="submit">Szukaj →</button></form><?php endif; ?>
<div class="qrp-content-grid" data-grid><?php qrp_cards($query->posts); ?></div><p data-content-status role="status"><?php if(!$query->post_count) echo 'Pierwsze historie pojawią się tutaj wkrótce.'; ?></p><button class="qrp-outline" data-more <?php if($query->max_num_pages<2) echo 'hidden'; ?>>Odkryj więcej historii ↓</button></section>
<?php break; case 'map': ?>
<section id="mapa" class="qrp-section qrp-map-section"><div class="qrp-map-intro"><p class="qrp-eyebrow">KAŻDE MIEJSCE MA SWOJĄ HISTORIĘ</p><h2><?php echo esc_html($s['map_title']); ?></h2><p><?php echo esc_html($s['map_text']); ?></p><button class="qrp-button" data-open-map>Otwórz mapę <span>↗</span></button></div><div class="qrp-map-art" <?php if($s['map_image']) echo 'style="background-image:url(\''.esc_url(qrp_image($s['map_image'])).'\')"'; ?> aria-hidden="true"><span class="qrp-map-pin pin-1">●</span><span class="qrp-map-pin pin-2">●</span><span class="qrp-map-pin pin-3">●</span></div>
<div class="qrp-map-panel" hidden data-map-panel data-lat="<?php echo esc_attr($s['map_lat']); ?>" data-lng="<?php echo esc_attr($s['map_lng']); ?>" data-zoom="<?php echo absint($s['map_zoom']); ?>"><p>Mapa korzysta z OpenStreetMap. Otwarcie mapy pobierze mapę z zewnętrznego serwisu.</p><div data-map-frame></div><div data-locations></div><p data-map-status role="status"></p><button class="qrp-outline" data-close-map>Zamknij mapę</button></div></section>
<?php break; case 'about': ?>
<section id="projekt" class="qrp-section qrp-about"><div><p class="qrp-eyebrow">O PROJEKCIE</p><h2><?php echo esc_html($s['about_title']); ?></h2></div><div><p><?php echo nl2br(esc_html($s['about_text'])); ?></p><?php if($s['about_image']): ?><img src="<?php echo esc_url(qrp_image($s['about_image'])); ?>" alt="" loading="lazy"><?php endif; ?></div></section>
<?php break; endswitch; endforeach; ?></div>
