<?php defined('ABSPATH') || exit; $hero=qrp_image($s['hero_image'])?:QRP_URL.'assets/hero.jpg'; ?>
<div class="qrp-landing qrp-font-<?php echo esc_attr($s['font']); ?>">
<section class="qrp-hero" style="--hero-image:url('<?php echo esc_url($hero); ?>')"><div class="qrp-hero-inner"><p class="qrp-eyebrow"><?php echo esc_html($s['hero_eyebrow']); ?></p><h1><?php echo nl2br(esc_html($s['hero_title'])); ?></h1><p class="qrp-hero-text"><?php echo esc_html($s['hero_text']); ?></p><a class="qrp-button" href="<?php echo esc_url($s['hero_button_url']); ?>"><?php echo esc_html($s['hero_button']); ?> <span aria-hidden="true">→</span></a><p class="qrp-hero-caption">53°55′ N &nbsp; 18°41′ E <span>Pomorskie · Kociewie</span></p></div>
<?php if($s['show_qr_badge']): ?><div class="qrp-scan-badge" aria-label="Odkrywaj treści za pomocą kodów QR"><svg viewBox="0 0 60 60" aria-hidden="true"><path fill="currentColor" d="M2 2h20v20H2zm4 4v12h12V6zM38 2h20v20H38zm4 4v12h12V6zM2 38h20v20H2zm4 4v12h12V42zM10 10h4v4h-4zm36 0h4v4h-4zM10 46h4v4h-4zM26 2h6v12h-6zm0 18h8v8h-8zm12 6h8v8h-8zm12 0h8v14h-8zM26 34h8v8h-8zm12 4h8v8h-8zm-12 8h8v12h-8zm12 6h8v6h-8zm12-8h8v14h-8z"/></svg><span>ZESKANUJ<br>ODKRYJ<br>POZNAJ</span></div><?php endif; ?><span class="qrp-hero-index">01 / ODKRYWAJ</span></section>
<?php foreach($s['modules'] as $module): if(!$module['enabled']) continue; switch($module['type']): case 'features': ?>
<section class="qrp-features" aria-label="Odkrywaj Pelplin"><?php foreach($s['features'] as $feature): ?><a href="<?php echo esc_url($feature['url']); ?>"><?php echo qrp_icon($feature['icon']); ?><span><?php echo esc_html($feature['title']); ?></span></a><?php endforeach; ?></section>
<?php break; case 'categories': $categories=get_terms(['taxonomy'=>'qrp_category','hide_empty'=>false,'number'=>$s['category_count']]); ?>
<section id="kategorie" class="qrp-section"><div class="qrp-section-heading"><div><p class="qrp-eyebrow">OD HISTORII DO CODZIENNOŚCI</p><h2><?php echo esc_html($s['categories_title']); ?></h2></div><a href="#tresci" class="qrp-text-link">Zobacz treści <span>→</span></a></div><div class="qrp-category-grid">
<?php if(!is_wp_error($categories)) foreach($categories as $index=>$term): $img=qrp_image($s['category_images'][$term->term_id]??0)?:QRP_URL.'assets/hero.jpg'; ?><a class="qrp-category" href="<?php echo esc_url(get_term_link($term)); ?>"><img src="<?php echo esc_url($img); ?>" alt="" loading="lazy"><div><span class="qrp-category-number"><?php echo esc_html(sprintf('%02d',$index+1)); ?></span><h3><?php echo esc_html($term->name); ?></h3><span class="qrp-circle" aria-hidden="true">→</span></div></a><?php endforeach; ?>
</div></section>
<?php break; case 'content': $query=qrp_content_query(); ?>
<section id="tresci" class="qrp-section" data-content data-count="<?php echo absint($s['content_count']); ?>"><div class="qrp-section-heading"><div><p class="qrp-eyebrow">MIEJSCA, LUDZIE, OPOWIEŚCI</p><h2><?php echo esc_html($s['content_title']); ?></h2></div><span class="qrp-total"><?php echo absint($query->found_posts); ?> treści</span></div>
<?php if($s['show_search']): ?><form class="qrp-search" role="search"><label class="screen-reader-text" for="qrp-search">Szukaj treści</label><input id="qrp-search" name="search" placeholder="Szukaj historii, miejsc, ciekawostek…" type="search"><label class="screen-reader-text" for="qrp-category">Kategoria</label><select id="qrp-category" name="category"><option value="">Wszystkie kategorie</option><?php $terms=get_terms(['taxonomy'=>'qrp_category','hide_empty'=>false]);if(!is_wp_error($terms))foreach($terms as $t)echo '<option value="'.absint($t->term_id).'">'.esc_html($t->name).'</option>'; ?></select><button class="qrp-button" type="submit">Szukaj →</button></form><?php endif; ?>
<div class="qrp-content-grid" data-grid><?php qrp_cards($query->posts); ?></div><p data-content-status role="status"><?php if(!$query->post_count) echo 'Pierwsze historie pojawią się tutaj wkrótce.'; ?></p><button class="qrp-outline" data-more <?php if($query->max_num_pages<2) echo 'hidden'; ?>>Odkryj więcej historii ↓</button></section>
<?php break; case 'map': ?>
<section id="mapa" class="qrp-section qrp-map-section"><div class="qrp-map-intro"><p class="qrp-eyebrow">KAŻDE MIEJSCE MA SWOJĄ HISTORIĘ</p><h2><?php echo esc_html($s['map_title']); ?></h2><p><?php echo esc_html($s['map_text']); ?></p><button class="qrp-button" data-open-map>Otwórz mapę <span>↗</span></button></div><div class="qrp-map-art" <?php if($s['map_image']) echo 'style="background-image:url(\''.esc_url(qrp_image($s['map_image'])).'\')"'; ?> aria-hidden="true"><span class="qrp-map-pin pin-1">●</span><span class="qrp-map-pin pin-2">●</span><span class="qrp-map-pin pin-3">●</span></div>
<div class="qrp-map-panel" hidden data-map-panel data-lat="<?php echo esc_attr($s['map_lat']); ?>" data-lng="<?php echo esc_attr($s['map_lng']); ?>" data-zoom="<?php echo absint($s['map_zoom']); ?>"><p>Mapa korzysta z OpenStreetMap. Otwarcie mapy pobierze mapę z zewnętrznego serwisu.</p><div data-map-frame></div><div data-locations></div><p data-map-status role="status"></p><button class="qrp-outline" data-close-map>Zamknij mapę</button></div></section>
<?php break; case 'about': ?>
<section id="projekt" class="qrp-section qrp-about"><div><p class="qrp-eyebrow">O PROJEKCIE</p><h2><?php echo esc_html($s['about_title']); ?></h2></div><div><p><?php echo nl2br(esc_html($s['about_text'])); ?></p><?php if($s['about_image']): ?><img src="<?php echo esc_url(qrp_image($s['about_image'])); ?>" alt="" loading="lazy"><?php endif; ?></div></section>
<?php break; endswitch; endforeach; ?></div>
