import {createApp, ref, reactive, computed, onMounted} from 'vue/dist/vue.esm-bundler.js';
const cfg=window.qrpAdmin;
const MediaField={props:['modelValue','label'],emits:['update:modelValue'],setup(props,{emit}){const images=reactive(Object.fromEntries(cfg.images.map(i=>[i.id,i.url])));return {images,choose(){const frame=window.wp.media({title:props.label,button:{text:'Użyj grafiki'},multiple:false,library:{type:'image'}});frame.on('select',()=>{const a=frame.state().get('selection').first().toJSON();images[a.id]=a.sizes?.medium?.url||a.url;emit('update:modelValue',a.id);});frame.open();}};},template:`<div class="qrpa-media"><label>{{label}}</label><div class="qrpa-media-preview"><img v-if="modelValue && images[modelValue]" :src="images[modelValue]" alt=""><span v-else>{{modelValue ? 'Grafika #'+modelValue : 'Grafika domyślna / brak'}}</span></div><button type="button" class="button" @click="choose">Wybierz z biblioteki</button> <button v-if="modelValue" type="button" class="button-link-delete" @click="$emit('update:modelValue',0)">Usuń</button></div>`};
const LinkList={props:['modelValue','title'],template:`<div><h3>{{title}}</h3><div v-for="(link,i) in modelValue" :key="i" class="qrpa-link-row"><label>Nazwa<input v-model="link.label"></label><label>Adres<input v-model="link.url" placeholder="https://… lub #tresci"></label><button type="button" class="button" @click="modelValue.splice(i,1)">Usuń</button><button type="button" class="button" :disabled="!i" @click="modelValue.splice(i-1,0,modelValue.splice(i,1)[0])">↑</button></div><button type="button" class="button" @click="modelValue.push({label:'Nowy link',url:'#tresci'})">+ Dodaj link</button></div>`};
createApp({components:{MediaField,LinkList},setup(){
  const initial=structuredClone(cfg.settings);initial.category_images={...initial.category_images};const s=reactive(initial),screen=ref(cfg.page==='qrp-settings'?'settings':cfg.page==='qrp-stats'?'stats':'overview'),tab=ref('hero'),busy=ref(false),message=ref(''),error=ref(''),days=ref(30),stats=ref({daily:[],top:[]}),dirty=ref(false),update=ref(null),checking=ref(false),updateError=ref('');
  const call=async(path,body)=>{const r=await fetch(cfg.api+path,{method:body?'POST':'GET',headers:{'X-WP-Nonce':cfg.nonce,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.message||'Nie udało się wykonać operacji.');return data;};
  async function refresh(){try{stats.value=await call('stats?days='+days.value);}catch(e){error.value=e.message;}}
  async function checkUpdate(){checking.value=true;updateError.value='';try{update.value=await call('updates',{});}catch(e){update.value=null;updateError.value=e.message;}finally{checking.value=false;}}
  async function save(){busy.value=true;error.value='';message.value='';try{Object.assign(s,await call('settings',s));dirty.value=false;message.value='Zapisano ustawienia. Zmiany są już widoczne na landing page.';}catch(e){error.value=e.message;}finally{busy.value=false;}}
  const scans=computed(()=>stats.value.daily.filter(d=>d.kind==='scan').reduce((n,d)=>n+Number(d.hits),0)),views=computed(()=>stats.value.daily.filter(d=>d.kind==='view').reduce((n,d)=>n+Number(d.hits),0)),visitors=computed(()=>stats.value.daily.filter(d=>d.kind==='scan').reduce((n,d)=>n+Number(d.visitors),0));
  const bars=computed(()=>{const rows=[];for(let i=Number(days.value)-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);rows.push({day:key,hits:Number(stats.value.daily.find(r=>r.day===key&&r.kind==='scan')?.hits||0)});}return rows;});
  const max=computed(()=>Math.max(1,...bars.value.map(b=>b.hits)));
  const names={features:'Skróty tematyczne',categories:'Kategorie',content:'Treści i wyszukiwarka',map:'Mapa',about:'O projekcie'};
  function move(i,delta){const target=i+delta;if(target<0||target>=s.modules.length)return;s.modules.splice(target,0,s.modules.splice(i,1)[0]);dirty.value=true;}
  onMounted(()=>{refresh();window.addEventListener('beforeunload',e=>{if(dirty.value){e.preventDefault();e.returnValue='';}});});
  return{cfg,s,screen,tab,busy,message,error,days,stats,scans,views,visitors,bars,max,names,dirty,save,refresh,move,update,checking,updateError,checkUpdate,
    tabs:[['hero','Nagłówek i hero'],['modules','Moduły i kolejność'],['categories','Kategorie i zdjęcia'],['navigation','Menu i stopka'],['map','Mapa i projekt'],['style','Wygląd i system'],['updates','Aktualizacje']]};
},template:`
<div class="qrpa" @input="dirty=true" @change="dirty=true">
  <aside class="qrpa-sidebar"><div class="qrpa-logo">QR<span>PELPLIN</span></div><p>MIASTO OPOWIADA</p><button :class="{active:screen==='overview'}" @click="screen='overview'">◈ Przegląd</button><a :href="cfg.posts">▤ Treści QR</a><button :class="{active:screen==='settings'}" @click="screen='settings'">◉ Wygląd i CMS</button><button :class="{active:screen==='stats'}" @click="screen='stats';refresh()">▥ Statystyki</button><a :href="cfg.preview" target="_blank" rel="noopener">↗ Otwórz portal</a><small>QR Pelplin {{cfg.version}}</small></aside>
  <div class="qrpa-main"><header class="qrpa-top"><div><span class="qrpa-eyebrow">PANEL ZARZĄDZANIA</span><h1>{{screen==='settings'?'Wygląd i CMS':screen==='stats'?'Statystyki portalu':'Twoje miasto. Twoje historie.'}}</h1></div><a class="qrpa-primary" :href="cfg.add">+ Dodaj treść QR</a></header>
  <p v-if="error" class="qrpa-error" role="alert">{{error}}</p><p v-if="message" class="qrpa-success" role="status">{{message}}</p>
  <template v-if="screen==='overview'"><div class="qrpa-metrics"><div><span>Wejścia przez QR · 30 dni</span><strong>{{scans}}</strong><small>Otwarcia stałego adresu QR</small></div><div><span>Odsłony treści · 30 dni</span><strong>{{views}}</strong><small>Także wejścia bezpośrednie</small></div><div><span>Kategorie</span><strong>{{cfg.categories.length}}</strong><small>Tematy, które łączą historie</small></div></div><section class="qrpa-panel qrpa-welcome"><div><span class="qrpa-eyebrow">OD POMYSŁU DO WYDRUKU</span><h2>Każde miejsce zasługuje<br>na swoją opowieść.</h2><p>Dodaj treść i zdjęcie, opublikuj wpis, a następnie wygeneruj QR w panelu wpisu. Kod zapisze się w bibliotece mediów jako SVG i PNG.</p><a class="qrpa-primary" :href="cfg.add">Stwórz pierwszą historię →</a></div><div class="qrpa-steps"><p><b>01</b> Dodaj historię w edytorze WordPress</p><p><b>02</b> Ustaw kategorię, zdjęcie i miejsce</p><p><b>03</b> Opublikuj, wygeneruj QR i pobierz pliki</p><p><b>04</b> Wydrukuj kod i obserwuj statystyki</p></div></section><section class="qrpa-panel"><h2>Gotowy do konfiguracji</h2><p>Landing page: <a :href="cfg.preview" target="_blank" rel="noopener">Otwórz podgląd →</a>. Aby używać go jako strony głównej, wybierz tę stronę w Ustawienia → Czytanie.</p><button class="button" @click="screen='settings'">Dostosuj landing page</button></section></template>
  <template v-if="screen==='settings'"><div class="qrpa-tabs"><button v-for="t in tabs" :key="t[0]" :class="{active:tab===t[0]}" @click="tab=t[0]">{{t[1]}}</button></div><form @submit.prevent="save"><section class="qrpa-panel">
    <template v-if="tab==='hero'"><h2>To tutaj zaczyna się odkrywanie</h2><p>Wszystkie zdjęcia wybierzesz z biblioteki mediów WordPressa.</p><div class="qrpa-columns"><MediaField @update:model-value="dirty=true" v-model="s.logo" label="Logo w nagłówku"/><MediaField @update:model-value="dirty=true" v-model="s.hero_image" label="Zdjęcie tła hero"/></div><label>Nazwa marki<input v-model="s.brand"></label><label>Tekst nad nagłówkiem<input v-model="s.hero_eyebrow"></label><label>Główny nagłówek<textarea v-model="s.hero_title" rows="2"></textarea></label><label>Opis<textarea v-model="s.hero_text" rows="3"></textarea></label><div class="qrpa-columns"><label>Przycisk<input v-model="s.hero_button"></label><label>Adres przycisku<input v-model="s.hero_button_url"></label></div><label class="qrpa-check"><input type="checkbox" v-model="s.show_qr_badge"> Pokaż dekoracyjny znak „Zeskanuj / Odkryj / Poznaj”</label></template>
    <template v-if="tab==='modules'"><h2>Ułóż landing page po swojemu</h2><p>Włączaj sekcje i zmieniaj ich kolejność strzałkami.</p><div class="qrpa-module" v-for="(m,i) in s.modules" :key="m.type"><label class="qrpa-check"><input type="checkbox" v-model="m.enabled">{{names[m.type]}}</label><div><button type="button" class="button" :disabled="i===0" @click="move(i,-1)">↑</button> <button type="button" class="button" :disabled="i===s.modules.length-1" @click="move(i,1)">↓</button></div></div><div class="qrpa-columns"><label>Liczba treści na stronie<input type="number" min="1" max="48" v-model.number="s.content_count"></label><label>Liczba kategorii<input type="number" min="1" max="24" v-model.number="s.category_count"></label></div><label>Nagłówek treści<input v-model="s.content_title"></label><label>Sortowanie treści<select v-model="s.content_order"><option value="date">Najnowsze</option><option value="title">Alfabetycznie</option><option value="menu_order">Kolejność ustawiona przy wpisach</option></select></label><label class="qrpa-check"><input type="checkbox" v-model="s.show_search"> Wyszukiwarka i filtr kategorii</label><h3>Skróty tematyczne</h3><div class="qrpa-feature" v-for="(f,i) in s.features" :key="i"><label>Nazwa<input v-model="f.title"></label><label>Ikona<select v-model="f.icon"><option v-for="icon in ['crown','map','image','people','book','pin']">{{icon}}</option></select></label><label>Kategoria<select v-model.number="f.category_id"><option :value="0">Dopasuj automatycznie</option><option v-for="c in cfg.categories" :value="c.id">{{c.name}}</option></select></label><label>Link zapasowy<input v-model="f.url"></label><button type="button" class="button" @click="s.features.splice(i,1);dirty=true">Usuń</button></div><button type="button" class="button" @click="s.features.push({title:'Nowy temat',icon:'pin',url:'#tresci'});dirty=true">+ Dodaj skrót</button></template>
    <template v-if="tab==='categories'"><h2>Kategorie ze zdjęciami</h2><label>Nagłówek sekcji<input v-model="s.categories_title"></label><div class="qrpa-columns"><MediaField @update:model-value="dirty=true" v-for="c in cfg.categories" :key="c.id" v-model="s.category_images[c.id]" :label="c.name"/></div><p>Kategorie dodasz i zmienisz w menu WordPress: QR Pelplin → Kategorie.</p></template>
    <template v-if="tab==='navigation'"><LinkList v-model="s.menu" title="Menu główne"/><LinkList v-model="s.footer_menu" title="Menu stopki"/><LinkList v-model="s.socials" title="Linki społecznościowe"/><hr><MediaField @update:model-value="dirty=true" v-model="s.footer_logo" label="Logo stopki"/><label>Tekst stopki<textarea v-model="s.footer_text"></textarea></label><label>Tekst copyright (rok dodawany automatycznie)<input v-model="s.copyright"></label></template>
    <template v-if="tab==='map'"><h2>Mapa treści</h2><label>Nagłówek mapy<input v-model="s.map_title"></label><label>Opis mapy<textarea v-model="s.map_text"></textarea></label><MediaField @update:model-value="dirty=true" v-model="s.map_image" label="Grafika w sekcji mapy"/><div class="qrpa-columns"><label>Środek — szerokość<input type="number" step="any" min="-90" max="90" v-model.number="s.map_lat"></label><label>Środek — długość<input type="number" step="any" min="-180" max="180" v-model.number="s.map_lng"></label><label>Przybliżenie<input type="number" min="3" max="18" v-model.number="s.map_zoom"></label></div><p>Miejsca pobierane są z opublikowanych treści z uzupełnionymi współrzędnymi. Mapa otwiera się dopiero po kliknięciu.</p><hr><h2>O projekcie</h2><label>Nagłówek<input v-model="s.about_title"></label><label>Opis<textarea rows="5" v-model="s.about_text"></textarea></label><MediaField @update:model-value="dirty=true" v-model="s.about_image" label="Zdjęcie projektu"/></template>
    <template v-if="tab==='updates'"><h2>Aktualizacje z GitHuba</h2><p>Wersja zainstalowana: <strong>{{cfg.version}}</strong>. Sprawdź dostępność najnowszego opublikowanego wydania.</p><button type="button" class="qrpa-primary" @click="checkUpdate" :disabled="checking">{{checking?'Sprawdzanie…':'Sprawdź aktualizacje na GitHubie'}}</button><p v-if="updateError" class="qrpa-error" role="alert">{{updateError}}</p><div v-if="update" class="qrpa-update-result" role="status"><h3>{{update.message}}</h3><p>Najnowsza wersja: <strong>{{update.latest}}</strong></p><a v-if="update.update_url" class="qrpa-primary" :href="update.update_url">Zaktualizuj do {{update.latest}} →</a><p v-if="update.available && !update.can_update">Twoje konto lub konfiguracja WordPressa nie pozwala na instalowanie aktualizacji. Skontaktuj się z administratorem.</p><p><a :href="update.release_url" target="_blank" rel="noopener">Zobacz informacje o wydaniu ↗</a></p></div><p>Przycisk aktualizacji uruchamia instalator WordPressa. Jeżeli hosting wymaga danych FTP, WordPress wyświetli odpowiedni formularz. Treści, ustawienia i stałe kody QR pozostają zachowane.</p></template>
    <template v-if="tab==='style'"><h2>Wygląd portalu</h2><div class="qrpa-columns"><label>Akcent<input type="color" v-model="s.accent"></label><label>Tło<input type="color" v-model="s.background"></label><label>Tekst<input type="color" v-model="s.text_color"></label></div><label>Typografia<select v-model="s.font"><option value="classic">Klasyczne nagłówki szeryfowe</option><option value="modern">Nowoczesne nagłówki bezszeryfowe</option></select></label><label>Strona landing page<select v-model.number="s.landing_page"><option :value="0">Tylko shortcode</option><option v-for="p in cfg.pages" :value="p.id">{{p.title}}</option></select></label><p>Shortcode: <code>[qr_pelplin_landing]</code>. Wybrana strona korzysta z pełnego szablonu wtyczki.</p><hr><h2>Kody QR i pomiar</h2><label>Rozdzielczość PNG<select v-model.number="s.qr_size"><option :value="512">512 × 512</option><option :value="1024">1024 × 1024</option><option :value="2048">2048 × 2048</option></select></label><label class="qrpa-check"><input type="checkbox" v-model="s.analytics_enabled"> Zbieraj statystyki wejść i odsłon</label><label>Przechowywanie statystyk (dni)<input type="number" min="7" max="730" v-model.number="s.retention_days"></label><p>Statystyki nie zapisują surowych adresów IP. Przybliżone rozpoznawanie odwiedzających działa w obrębie dnia i treści. Wejścia administratorów/autorów oraz rozpoznanych botów są pomijane.</p></template>
  </section><div class="qrpa-save"><span>{{dirty?'Masz niezapisane zmiany':'Ustawienia portalu'}}</span><button class="qrpa-primary" type="submit" :disabled="busy">{{busy?'Zapisywanie…':'Zapisz ustawienia'}}</button><a :href="cfg.preview" target="_blank" rel="noopener">Otwórz podgląd ↗</a></div></form></template>
  <template v-if="screen==='stats'"><div class="qrpa-stats-filter"><label>Okres<select v-model.number="days" @change="refresh"><option :value="7">7 dni</option><option :value="30">30 dni</option><option :value="90">90 dni</option><option :value="365">365 dni</option></select></label><a class="button" :href="cfg.export+'&days='+days">Pobierz CSV</a><button class="button" @click="refresh">Odśwież</button></div><div class="qrpa-metrics"><div><span>Wejścia przez QR</span><strong>{{scans}}</strong><small>Otwarcia adresu QR</small></div><div><span>Odsłony treści</span><strong>{{views}}</strong><small>Wszystkie źródła wejść</small></div><div><span>Suma dziennych odwiedzających QR</span><strong>{{visitors}}</strong><small>Nie jest to liczba unikalnych osób w okresie</small></div></div><section class="qrpa-panel"><h2>Wejścia przez QR w czasie</h2><div class="qrpa-chart" role="img" :aria-label="'Wykres: '+scans+' wejść QR w okresie '+days+' dni'"><div v-for="b in bars" :key="b.day" class="qrpa-bar" :title="b.day+': '+b.hits"><span :style="{height:Math.max(2,b.hits/max*100)+'%'}"></span></div></div><div class="qrpa-chart-labels"><span>{{stats.from}}</span><span>{{stats.to}}</span></div><p v-if="!scans">Statystyki pojawią się po pierwszym otwarciu adresu QR przez odwiedzającego.</p></section><section class="qrpa-panel"><h2>Najczęściej odkrywane treści</h2><div class="qrpa-table-wrap"><table><thead><tr><th>Treść</th><th>Rodzaj</th><th>Wejścia</th><th>Odwiedzający / dzień (suma)</th></tr></thead><tbody><tr v-for="r in stats.top" :key="r.post_id+r.kind"><td><a :href="r.edit_url">{{r.title}}</a></td><td>{{r.kind==='scan'?'QR':'Odsłona'}}</td><td>{{r.hits}}</td><td>{{r.visitors}}</td></tr></tbody></table></div><p>Pomiar dotyczy otwarć linku, a nie samego rozpoznania QR aparatem. Ponowne wejścia w ciągu 5 sekund są pomijane. Dane są przybliżone; cache/CDN, blokowanie JavaScript i nierozpoznane boty mogą wpływać na wynik.</p></section></template>
  </div></div>`}).mount('#qrp-admin');
