import {ref,reactive,onMounted,onBeforeUnmount,nextTick,watch} from 'vue/dist/vue.esm-bundler.js';
import L from 'leaflet';import 'leaflet/dist/leaflet.css';
import FileIcon from './file-icon.js';
import RichField from './rich-field.js';
const cfg=window.qrpAdmin;
const uid=()=>crypto.randomUUID().replaceAll('-','');
const blank=()=>({seo_title:'',seo_description:'',seo_noindex:false,id:0,title:'',excerpt:'',slug:'',status:'draft',sections:[{uid:uid(),html:''}],categories:[],thumbnail:null,gallery:[],attachments:[],primary:null,delivery:'auto',lat:'',lng:'',address:'',qr_png:'',qr_svg:''});
const call=async(path,body,method)=>{const r=await fetch(cfg.api+path,{method:method||(body?'POST':'GET'),headers:{'X-WP-Nonce':cfg.nonce,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.message||'Operacja nie powiodła się.');return data;};
const RichText={props:['section'],emits:['change','focus'],setup(props,{emit}){const id='qrp-rich-'+props.section.uid;
 onMounted(async()=>{await nextTick();if(document.readyState==='loading')await new Promise(resolve=>document.addEventListener('DOMContentLoaded',resolve,{once:true}));window.wp.editor.initialize(id,{tinymce:{height:260,content_style:'strong,b{color:'+cfg.settings.accent+'}',menubar:false,toolbar1:'formatselect bold italic underline bullist numlist blockquote link unlink undo redo',toolbar2:'alignleft aligncenter alignright removeformat',plugins:'lists paste wordpress wplink wpdialogs wpeditimage',setup(editor){editor.on('change input undo redo',()=>{props.section.html=editor.getContent();emit('change');});editor.on('focus',()=>emit('focus',id));}},quicktags:false,mediaButtons:false});});
 onBeforeUnmount(()=>window.wp.editor.remove(id));return{id};},template:`<textarea :id="id" :value="section.html" class="qrpc-rich-fallback" @input="section.html=$event.target.value;$emit('change')"></textarea>`};
export default {components:{RichText,RichField,FileIcon},emits:['dirty-change'],setup(props,{emit}){
 const entry=reactive(blank()),items=ref([]),listPages=ref(1),listPage=ref(1),search=ref(''),mode=ref('list'),busy=ref(false),error=ref(''),notice=ref(''),dirty=ref(false),activeEditor=ref(''),categories=ref([...cfg.categories]),categoryName=ref(''),mapNode=ref(null),mapOpen=ref(false);let map,marker;watch(()=>dirty.value,value=>emit('dirty-change',value));
 const chooseCenter=()=>{if(map)setPoint(map.getCenter());};
 const imageAsset=a=>({id:a.id,title:a.title,url:a.url,mime:a.mime,type:a.type,thumbnail:a.sizes?.medium?.url||a.url});
 async function list(){try{const d=await call('entries?page='+listPage.value+'&search='+encodeURIComponent(search.value));items.value=d.items;listPages.value=d.pages;}catch(e){error.value=e.message;}}
 function cleanMap(){if(map){map.remove();map=null;marker=null;}mapOpen.value=false;}
 async function edit(id=0){if(dirty.value&&!window.confirm('Odrzucić niezapisane zmiany?'))return;cleanMap();mode.value='loading';error.value='';notice.value='';try{Object.assign(entry,id?await call('entries/'+id):blank());if(!entry.sections.length)entry.sections=[{uid:uid(),html:''}];mode.value='edit';dirty.value=false;activeEditor.value='';const url=new URL(location.href);url.searchParams.delete('new');if(id)url.searchParams.set('item',id);else url.searchParams.delete('item');history.replaceState(null,'',url);}catch(e){error.value=e.message;mode.value='list';}}
 async function save(status=entry.status){busy.value=true;error.value='';notice.value='';try{for(const section of entry.sections){const editor=window.tinymce?.get('qrp-rich-'+section.uid);if(editor)section.html=editor.getContent();}const data=await call('entries'+(entry.id?'/'+entry.id:''),{...entry,status});Object.assign(entry,data);dirty.value=false;notice.value='Zapisano treść.';const url=new URL(location.href);url.searchParams.set('item',entry.id);history.replaceState(null,'',url);await nextTick();window.scrollTo({top:0,left:0,behavior:'instant'});document.querySelector('.qrpc [data-save-notice]')?.focus({preventScroll:true});return true;}catch(e){error.value=e.message;return false;}finally{busy.value=false;}}
 function media(key,multiple=false){const frame=window.wp.media({title:key==='gallery'?'Galeria zdjęć':'Wybierz materiały',button:{text:'Dołącz'},multiple,library:['thumbnail','gallery'].includes(key)?{type:'image'}:{}});frame.on('select',()=>{const files=frame.state().get('selection').toJSON().map(imageAsset);if(multiple)entry[key]=[...new Map([...entry[key],...files].map(f=>[f.id,f])).values()];else entry[key]=files[0]||null;dirty.value=true;});frame.open();}
 function insertAsset(asset,kind='file'){let id=activeEditor.value;if(!id&&entry.sections.length)id='qrp-rich-'+entry.sections.at(-1).uid;const editor=window.tinymce?.get(id),marker='[qrp_'+kind+' id="'+asset.id+'"]';if(editor){editor.insertContent('<p>'+marker+'</p>');const section=entry.sections.find(s=>'qrp-rich-'+s.uid===id);if(section)section.html=editor.getContent();}else entry.sections.push({uid:uid(),html:'<p>'+marker+'</p>'});dirty.value=true;}
 function insertPhoto(photo){insertAsset(photo,'image');}
 function move(rows,i,d){if(i+d<0||i+d>=rows.length)return;if(rows===entry.sections){for(const section of rows){const editor=window.tinymce?.get('qrp-rich-'+section.uid);if(editor)section.html=editor.getContent();window.wp.editor.remove('qrp-rich-'+section.uid);section.uid=uid();}activeEditor.value='';}rows.splice(i+d,0,rows.splice(i,1)[0]);dirty.value=true;}
 function setPoint(point){entry.lat=point.lat.toFixed(6);entry.lng=(((point.lng+180)%360+360)%360-180).toFixed(6);dirty.value=true;const position=[Number(entry.lat),Number(entry.lng)];if(marker)marker.setLatLng(position);else{marker=L.marker(position,{draggable:true,icon:L.divIcon({className:'qrpc-map-pin',html:'●',iconSize:[26,26],iconAnchor:[13,13]})}).addTo(map);marker.on('dragend',()=>setPoint(marker.getLatLng()));}}
 async function openMap(){mapOpen.value=true;await nextTick();if(!map){const has=entry.lat!==''&&entry.lng!=='';map=L.map(mapNode.value,{center:has?[Number(entry.lat),Number(entry.lng)]:[cfg.settings.map_lat,cfg.settings.map_lng],zoom:has?17:14});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors'}).addTo(map);map.on('click',e=>setPoint(e.latlng));if(has)setPoint({lat:Number(entry.lat),lng:Number(entry.lng)});}map.invalidateSize();}
 function clearMap(){entry.lat='';entry.lng='';if(marker){map.removeLayer(marker);marker=null;}dirty.value=true;}
 async function addCategory(){if(!categoryName.value.trim())return;try{const category=await call('entry-categories',{name:categoryName.value});if(!categories.value.some(c=>c.id===category.id))categories.value.push(category);entry.categories.push(category.id);categoryName.value='';dirty.value=true;}catch(e){error.value=e.message;}}
 async function trash(row){if(!window.confirm('Przenieść wpis do kosza? Wydrukowany QR przestanie prowadzić do treści.'))return;try{await call('entries/'+row.id,null,'DELETE');await list();}catch(e){error.value=e.message;}}
 async function back(){if(dirty.value&&!window.confirm('Odrzucić niezapisane zmiany?'))return;cleanMap();mode.value='list';dirty.value=false;const url=new URL(location.href);url.searchParams.delete('item');url.searchParams.delete('new');history.replaceState(null,'',url);await list();}
 onMounted(()=>{if(Number(cfg.entryId)||cfg.newEntry)edit(Number(cfg.entryId)||0);else list();window.addEventListener('beforeunload',guard);});
 function guard(e){if(dirty.value){e.preventDefault();e.returnValue='';}}onBeforeUnmount(()=>{cleanMap();window.removeEventListener('beforeunload',guard);});
 return{cfg,entry,items,listPages,listPage,search,mode,busy,error,notice,dirty,activeEditor,categories,categoryName,addCategory,mapNode,mapOpen,uid,list,edit,save,media,insertPhoto,insertAsset,move,openMap,chooseCenter,setPoint,clearMap,trash,back};
},template:`<div class="qrpc">
<p v-if="error" class="qrpa-error" role="alert">{{error}}</p><p v-if="notice" class="qrpa-success" role="status" tabindex="-1" data-save-notice>{{notice}}</p>
<template v-if="mode==='list'"><div class="qrpc-list-toolbar"><form @submit.prevent="listPage=1;list()"><input v-model="search" placeholder="Szukaj treści QR…" aria-label="Szukaj treści QR"><button class="button">Szukaj</button></form><button class="qrpa-primary" @click="edit()">+ Nowa treść QR</button></div><section class="qrpa-panel"><div class="qrpa-table-wrap"><table><thead><tr><th>Tytuł</th><th>Status</th><th>Zmieniono</th><th>Akcje</th></tr></thead><tbody><tr v-for="row in items" :key="row.id"><td><button class="qrpc-title-link" @click="edit(row.id)">{{row.title||'Bez tytułu'}}</button></td><td>{{row.status==='publish'?'Opublikowany':row.status==='draft'?'Szkic':row.status==='private'?'Prywatny':'Do akceptacji'}}</td><td>{{row.modified}}</td><td><button class="button" @click="edit(row.id)">Edytuj</button> <button class="button" @click="trash(row)">Kosz</button></td></tr></tbody></table><p v-if="!items.length">Dodaj pierwszą treść QR.</p></div><div class="qrpc-pagination"><button class="button" :disabled="listPage<=1" @click="listPage--;list()">←</button><span>{{listPage}} / {{Math.max(1,listPages)}}</span><button class="button" :disabled="listPage>=listPages" @click="listPage++;list()">→</button></div></section></template>
<p v-if="mode==='loading'">Ładowanie treści…</p>
<form v-if="mode==='edit'" @submit.prevent="save()" @input="dirty=true" @change="dirty=true"><div class="qrpc-editor-toolbar"><button type="button" class="button" @click="back">← Lista treści</button><span>{{dirty?'Niezapisane zmiany':'Treść QR'}}</span><a v-if="entry.id" :href="entry.url" target="_blank" rel="noopener">Podgląd ↗</a></div>
<div class="qrpc-editor-grid"><div><section class="qrpa-panel"><label>Tytuł<input v-model="entry.title" required placeholder="Jaką historię opowiada to miejsce?"></label><label>Krótki opis na kafelku<RichField v-model="entry.excerpt" @update:modelValue="dirty=true"/></label></section>
<section class="qrpa-panel"><h2>Treść</h2><p>Dodawaj osobne sekcje tekstowe. Zdjęcia i pliki wstawiasz jako krótkie znaczniki ID. Na stronie pokażą się zdjęcia, odtwarzacze i podglądy PDF.</p><div v-for="(section,i) in entry.sections" :key="section.uid" class="qrpc-text-section"><div><strong>Sekcja {{i+1}}</strong><button type="button" class="button" :disabled="!i" @click="move(entry.sections,i,-1)">↑</button><button type="button" class="button" :disabled="i===entry.sections.length-1" @click="move(entry.sections,i,1)">↓</button><button type="button" class="button" @click="entry.sections.splice(i,1);dirty=true">Usuń</button></div><RichText :section="section" @change="dirty=true" @focus="activeEditor=$event"/></div><button type="button" class="button" @click="entry.sections.push({uid:uid(),html:''});dirty=true">+ Dodaj sekcję tekstową</button></section>
<section class="qrpa-panel"><h2>Galeria zdjęć</h2><button type="button" class="button" @click="media('gallery',true)">+ Dodaj zdjęcia</button><div class="qrpc-gallery"><div v-for="(photo,i) in entry.gallery" :key="photo.id"><img :src="photo.thumbnail||photo.url" alt=""><span>{{photo.title}}</span><button type="button" class="button" @click="insertPhoto(photo)">Wstaw do tekstu</button><div><button type="button" class="button" :disabled="!i" @click="move(entry.gallery,i,-1)">↑</button> <button type="button" class="button" @click="entry.gallery.splice(i,1);dirty=true">Usuń</button></div></div></div></section>
<section class="qrpa-panel"><h2>Załączniki</h2><p>Dodaj wiele plików. Wstawione w treść nie będą powtarzane w sekcjach pod wpisem.</p><button type="button" class="button" @click="media('attachments',true)">+ Dodaj pliki</button><div v-for="(file,i) in entry.attachments" :key="file.id" class="qrpc-file"><FileIcon :file="file"/><label>Wyświetlana nazwa<input v-model="file.display_name" :placeholder="file.title" @input="dirty=true"></label><button type="button" class="button" @click="insertAsset(file)">Wstaw do tekstu</button><button type="button" class="button" :disabled="!i" @click="move(entry.attachments,i,-1)">↑</button><button type="button" class="button" @click="entry.attachments.splice(i,1);dirty=true">Usuń</button></div></section>
<section class="qrpa-panel"><h2>Miejsce na mapie</h2><label>Nazwa / adres miejsca<input v-model="entry.address"></label><button type="button" class="button" @click="openMap">Wskaż miejsce na mapie</button> <button type="button" class="button" @click="clearMap">Usuń punkt</button><div v-show="mapOpen" ref="mapNode" class="qrpc-map" tabindex="0" @keydown.enter.prevent="chooseCenter"></div><p v-if="entry.lat!==''">Lokalizacja wybrana. Kliknij mapę lub przeciągnij znacznik, aby ją zmienić.</p></section></div>
<aside><section class="qrpa-panel qrpc-publish"><h2>Publikacja</h2><label>Status<select v-model="entry.status"><option value="draft">Szkic</option><option value="pending">Do akceptacji</option><option v-if="cfg.canPublish" value="publish">Opublikowany</option><option v-if="cfg.canPublish" value="private">Prywatny</option></select></label><label>Adres wpisu<input v-model="entry.slug" placeholder="Utworzony z tytułu"></label><button class="qrpa-primary" type="submit" :disabled="busy">{{busy?'Zapisywanie…':'Zapisz treść'}}</button><button v-if="cfg.canPublish && entry.status!=='publish'" type="button" class="button" :disabled="busy" @click="save('publish')">Opublikuj</button></section>
<section class="qrpa-panel"><h2>Kategorie</h2><label v-for="c in categories" :key="c.id" class="qrpa-check"><input type="checkbox" v-model="entry.categories" :value="c.id">{{c.name}}</label><div v-if="cfg.canCategories"><input v-model="categoryName" placeholder="Nazwa nowej kategorii" aria-label="Nazwa nowej kategorii"><button type="button" class="button" @click="addCategory">+ Dodaj kategorię</button></div></section>
<section class="qrpa-panel"><h2>Miniatura</h2><img v-if="entry.thumbnail" class="qrpc-thumbnail" :src="entry.thumbnail.thumbnail||entry.thumbnail.url" alt=""><button type="button" class="button" @click="media('thumbnail')">Wybierz obraz</button> <button v-if="entry.thumbnail" type="button" class="button" @click="entry.thumbnail=null;dirty=true">Usuń</button></section>
<section class="qrpa-panel"><h2>Prezentacja po QR</h2><label>Tryb<select v-model="entry.delivery"><option value="auto">Automatycznie</option><option value="content">Treść i materiały</option><option value="preview">Podgląd pliku</option><option value="download">Pobierz plik</option><option value="audio">Odtwarzacz audio</option></select></label><p>PDF otwiera się w czytniku. Dla trybu pojedynczego pliku wybierz plik główny.</p><button type="button" class="button" @click="media('primary')">Wybierz plik główny</button><div v-if="entry.primary" class="qrpc-primary-file"><FileIcon :file="entry.primary"/><label>Wyświetlana nazwa<input v-model="entry.primary.display_name" :placeholder="entry.primary.title" @input="dirty=true"></label><button type="button" class="button" @click="insertAsset(entry.primary)">Wstaw do tekstu</button><button type="button" class="button" @click="entry.primary=null;dirty=true">Usuń</button></div></section>
<section class="qrpa-panel"><h2>SEO wpisu</h2><label>Tytuł w wyszukiwarce<input v-model="entry.seo_title" maxlength="200" placeholder="Domyślnie tytuł wpisu"></label><label>Opis w wyszukiwarce<textarea v-model="entry.seo_description" rows="3" maxlength="500" placeholder="Domyślnie krótki opis lub fragment treści"></textarea></label><label class="qrpa-check"><input type="checkbox" v-model="entry.seo_noindex"> Nie indeksuj tego wpisu</label></section><section class="qrpa-panel"><h2>Kod QR</h2><p>Kod powstaje automatycznie po publikacji, tylko raz. Jego cel zmienisz w zakładce Kody QR.</p><img v-if="entry.qr_png" class="qrpc-qr-preview" :src="entry.qr_png" alt="Kod QR"><p><a v-if="entry.qr_svg" :href="entry.qr_svg" download>Pobierz SVG</a> <a v-if="entry.qr_png" :href="entry.qr_png" download>Pobierz PNG</a></p><p v-if="entry.status!=='publish'">Opublikuj wpis przed wydrukowaniem QR.</p></section></aside></div>
<div class="qrpa-save"><span>{{dirty?'Masz niezapisane zmiany':'Treść zapisana'}}</span><button class="qrpa-primary" :disabled="busy">Zapisz treść</button></div></form></div>`};
